; directory
UNITTEST_RUNNER_FILE=
SLOWTEST_RUNNER_FILE=
PYTEST_RUNNER_FILE=
THIS_VERSION_PYTHON_FILE=
; env
DEFAULT_CONDA_ENV=
WINDOWS_CONDA_ENV_ARRAY=
LINUX_CONDA_ENV_ARRAY=
; quality
METRICS_EXCLUDE=
COVERAGE_SOURCE=
COVERAGE_OMIT=
COVERAGE_OMIT_EQUAL_METRICS_EXCLUDE=
FLAKE8_EXCLUDE=